apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "beetle-etcd.fullname" . }}
  labels:
    {{- include "beetle-etcd.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
     matchLabels:
      {{- include "beetle-etcd.selectorLabels" . | nindent 6 }}
