apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "beetle-etcd.fullname" . }}-etcd-data
  labels:
    app: {{ template "beetle-etcd.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | default "manual" }}
