apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "beetle-etcd.fullname" . }}
  labels:
    {{- include "beetle-etcd.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "beetle-etcd.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "beetle-etcd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "beetle-etcd.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "beetle-etcd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - /usr/local/bin/etcd
          args:
            - --name
            - {{ printf "$(MY_POD_NAME)" }}
            - --data-dir
            - /etcd-data
            - --listen-client-urls
            - http://0.0.0.0:2379
            - --advertise-client-urls
            - http://0.0.0.0:2379
            - --listen-peer-urls
            - http://0.0.0.0:2380
            - --initial-advertise-peer-urls
            - http://$(MY_POD_NAME).{{ include "beetle-etcd.fullname" . }}-headless.cloud-migrator.svc.cluster.local:2380
            - --initial-cluster
            - {{$name := include "beetle-etcd.fullname" . }}
              {{- $replicaCount := .Values.replicaCount | int }}
              {{- range $i := until $replicaCount }}
              {{- printf "%s-%d=http://%s-%d.%s-headless.cloud-migrator.svc.cluster.local:2380," $name $i $name $i $name }}
              {{- end }}
            - --initial-cluster-token
            - etcd-cluster
            - --initial-cluster-state
            - new
            - --log-level
            - info
            - --logger
            - zap
            - --log-outputs
            - stderr
            - --auth-token
            - simple
          ports:
            - name: client
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: peer
              containerPort: {{ .Values.service.peerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: etcd-data
              mountPath: /etcd-data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass | default "manual" }}
