apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tumblebug-etcd.fullname" . }}-etcd-data
  labels:
    {{- include "tumblebug-etcd.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | default "manual" }}
