replicaCount: 1

image:
  repository: cloudbaristaorg/airflow-server
  pullPolicy: IfNotPresent
  tag: "edge"

imagePullSecrets: []
nameOverride: "airflow-server"
fullnameOverride: "airflow-server"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 32080
  flowerPort: 5555
  flowerTargetPort: 5555
  flowerNodePort: 32555

resources:
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 20
  timeoutSeconds: 3
readinessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 20
  timeoutSeconds: 3

volumes: 
  - name: airflow-server-config
    configMap:
      name: airflow-server

volumeMounts:
  - name: airflow-server-config
    mountPath: /usr/local/airflow/airflow.cfg
    subPath: airflow.cfg
  - name: airflow-server-config
    mountPath: /usr/local/airflow/dags/dags.py
    subPath: dags.py
  - name: airflow-server-config
    mountPath: /usr/local/airflow/operators/json_http_request_operator.py
    subPath: json_http_request_operator.py
  - name: airflow-server-config
    mountPath: /usr/local/airflow/sample_dags/beetle_test.py
    subPath: beetle_test.py

persistence:
  enabled: false
  storageClass: "manual"
  accessMode: ReadWriteOnce
  size: 1Gi
  hostPath: /tmp/cloud-migrator/cm-cicada/airflow/server

airflow:
  username: airflow
  password: airflow_pass
  email: odt@test.com
  firstname: Oncloud
  lastname: DevTeam
  role: Admin

env: []
##############################################

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
