apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airflow-mysql.fullname" . }}
  labels:
    {{- include "airflow-mysql.labels" .  | nindent 4 }}
data:
  create_airflow_db.sql: |-
    {{ range .Files.Lines "files/conf/create_airflow_db.sql" }}
    {{ . }}
    {{ end }}