{{- if and (.Values.persistence.enabled) (eq "manual" .Values.persistence.storageClass) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "airflow-mysql.fullname" . }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
  persistentVolumeReclaimPolicy: Retain
{{- end -}}
