apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cm-honeybee.fullname" . }}
  labels:
    {{- include "cm-honeybee.labels" .  | nindent 4 }}
data:
  cm-honeybee.yaml: |-
    {{ range .Files.Lines "files/conf/cm-honeybee.yaml" }}
    {{ . }}
    {{ end }}
