apiVersion: v1
kind: Service
metadata:
  name: {{ include "cm-grasshopper.fullname" . }}
  labels:
    {{- include "cm-grasshopper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "cm-grasshopper.selectorLabels" . | nindent 4 }}
