replicaCount: 1

image:
  repository: cloudbaristaorg/cm-beetle
  pullPolicy: Always
  tag: "edge"

nameOverride: "cm-beetle"
fullnameOverride: "cm-beetle"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: NodePort
  port: 8056
  targetPort: 8056
  nodePort: 31056

livenessProbe:
  httpGet:
    path: /beetle/readyz
    port: 8056
    httpHeaders:
      - name: Authorization
        value: Basic ZGVmYXVsdDpkZWZhdWx0
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 3

readinessProbe:
  httpGet:
    path: /beetle/readyz
    port: 8056
    httpHeaders:
      - name: Authorization
        value: Basic ZGVmYXVsdDpkZWZhdWx0
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 3
  
volumes: 
  - name: beetle-volume-log
    persistentVolumeClaim:
      claimName: cm-beetle-log
  - name: beetle-volume-config
    configMap:
      name: cm-beetle
      items:
        - key: config.yaml
          path: config.yaml
        - key: setup.env
          path: setup.env

volumeMounts: 
  - name: beetle-volume-log
    mountPath: /app/log
  - name: beetle-volume-config
    mountPath: /app/conf/config.yaml
    subPath: config.yaml
  - name: beetle-volume-config
    mountPath: /app/conf/setup.env
    subPath: setup.env
    
persistence:
  db:
    enabled: false
    storageClass: "manual"
    accessMode: ReadWriteOnce
    size: 1Gi
    hostPath: /tmp/cloud-migrator/cm-beetle/db
  log:
    enabled: true
    storageClass: "manual"
    accessMode: ReadWriteOnce
    size: 1Gi
    hostPath: /tmp/cloud-migrator/cm-beetle/log


env:
  - name: BEETLE_ROOT
    value: /app
  - name: BEETLE_CBSTORE_ROOT
    value: /app
  - name: BEETLE_CBLOG_ROOT
    value: /app
  - name: BEETLE_TUMBLEBUG_REST_URL
    value: http://cb-tumblebug:1323/tumblebug
  - name: BEETLE_TUMBLEBUG_ENDPOINT
    value: http://cb-tumblebug:1323
  - name: BEETLE_LOGFILE_PATH
    value: /app/log/beetle.log
  - name: BEETLE_LOGFILE_MAXSIZE
    value: "1000"
  - name: BEETLE_LOGFILE_MAXBACKUPS
    value: "3"
  - name: BEETLE_LOGFILE_MAXAGE
    value: "30"
  - name: BEETLE_LOGFILE_COMPRESS
    value: "false"
  - name: BEETLE_LOGLEVEL
    value: info
  - name: BEETLE_NODE_ENV
    value: production
  - name: BEETLE_SQLITE_URL
    value: localhost:3306
  - name: BEETLE_SQLITE_DATABASE
    value: cm_beetle
  - name: BEETLE_SQLITE_USER
    value: cm_beetle
  - name: BEETLE_SQLITE_PASSWORD
    value: cm_beetle
  - name: BEETLE_API_ALLOW_ORIGINS
    value: "*"
  - name: BEETLE_API_AUTH_ENABLED
    value: "true"
  - name: BEETLE_API_USERNAME
    value: default
  - name: BEETLE_API_PASSWORD
    value: default
  - name: BEETLE_AUTOCONTROL_DURATION_MS
    value: "10000"
  - name: BEETLE_SELF_ENDPOINT
    value: cm-beetle:8056

#######################################

imagePullSecrets: []
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
ingress:
  enabled: false
resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
