replicaCount: 1

image:
  repository: cloudbaristaorg/cb-tumblebug
  pullPolicy: Always
  tag: "0.9.7"

imagePullSecrets: []
nameOverride: cb-tumblebug
fullnameOverride: cb-tumblebug

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name:

service:
  type: NodePort
  port: 1323
  targetPort: 1323
  nodePort: 31323

livenessProbe:
  httpGet:
    path: /tumblebug/readyz
    port: 1323
    httpHeaders:
      - name: Authorization
        value: Basic ZGVmYXVsdDpkZWZhdWx0
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 3

readinessProbe:
  httpGet:
    path: /tumblebug/readyz
    port: 1323
    httpHeaders:
      - name: Authorization
        value: Basic ZGVmYXVsdDpkZWZhdWx0
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 3
  
volumes: 
  - name: tumblebug-volume-db
    persistentVolumeClaim:
      claimName: cb-tumblebug-db
  - name: tumblebug-volume-log
    persistentVolumeClaim:
      claimName: cb-tumblebug-log
  - name: tumblebug-volume-config
    configMap:
      name: cb-tumblebug

volumeMounts: 
  - name: tumblebug-volume-db
    mountPath: /app/meta_db
  - name: tumblebug-volume-log
    mountPath: /app/log
  - name: tumblebug-volume-config
    mountPath: /app/conf
    
persistence:
  db:
    enabled: true
    storageClass: "manual"
    accessMode: ReadWriteOnce
    size: 1Gi
    hostPath: /tmp/cloud-migrator/cb-tumblebug/db
  log:
    enabled: true
    storageClass: "manual"
    accessMode: ReadWriteOnce
    size: 1Gi
    hostPath: /tmp/cloud-migrator/cb-tumblebug/log

env:
- name: TB_SPIDER_REST_URL
  value: "http://cb-spider:1024/spider"
- name: TB_ETCD_ENDPOINTS
  value: "http://tumblebug-etcd:2379"
- name: TB_AUTH_ENABLED
  value: "true"
- name: TB_API_USERNAME
  value: default
- name: TB_API_PASSWORD
  value: default
- name: TB_AUTOCONTROL_DURATION_MS
  value: "10000"
- name: TB_ROOT_PATH
  value: "/app"
- name: TB_SELF_ENDPOINT
  value: "cb-tumblebug:1323"


resources:
  requests:
    cpu: 100m
    memory: 128Mi

###################################################

nodeSelector: {}

tolerations: []

affinity: {}


ingress:
  enabled: false
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75
  

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

