apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cb-tumblebug.fullname" . }}
  labels:
    {{- include "cb-tumblebug.labels" .  | nindent 4 }}
data:
  cloud_conf.yaml: |-
    {{ range .Files.Lines "files/conf/cloud_conf.yaml" }}
    {{ . }}
    {{ end }}
