{{- if and (.Values.persistence.log.enabled) (eq "manual" .Values.persistence.log.storageClass) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "cb-tumblebug.fullname" . }}-log
spec:
  capacity:
    storage: {{ .Values.persistence.log.size }}
  accessModes:
    - {{ .Values.persistence.log.accessMode | quote }}
  storageClassName: {{ .Values.persistence.log.storageClass }}
  hostPath:
    path: {{ .Values.persistence.log.hostPath }}
  persistentVolumeReclaimPolicy: Retain
{{- end -}}
