replicaCount: 1

nameOverride: tumblebug-etcd
fullnameOverride: tumblebug-etcd

image:
  repository: gcr.io/etcd-development/etcd
  pullPolicy: IfNotPresent
  tag: "v3.5.14"

volumes: []

volumeMounts: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 2379
  targetPort: 2379
  peerPort: 2380
  peerTargetPort: 2380

livenessProbe:
  tcpSocket:
    port: 2379
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 3
  
readinessProbe:
  tcpSocket:
    port: 2379
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 3

persistence:
  enabled: true
  storageClass: "manual"
  accessMode: ReadWriteOnce
  size: 2Gi
  hostPath: /tmp/cloud-migrator/cb-tumblebug/etcd/data

########################################

imagePullSecrets: []

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


nodeSelector: {}

tolerations: []

affinity: {}
